# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.8.10


### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [2]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

import numpy as np

lista = list(range(1000000))
array = np.arange(1000000)

%time lista2 = [x * 2 for x in lista]
print(lista2[:50])
%time array2 = array * 2
print(array2[:50])

CPU times: user 122 ms, sys: 23.2 ms, total: 145 ms
Wall time: 146 ms
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]
CPU times: user 6.07 ms, sys: 587 µs, total: 6.66 ms
Wall time: 6.64 ms
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


### Exercício 2

In [3]:
# Exercício 2
# Crie um array de 10 elementos
# Altere os valores de todos os elementos dos índices 5 a 8 para 0
array = np.arange(10)
print(array)
array[5:9] = 0
print(array)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 0 0 0 0 9]


### Exercício 3

In [4]:
# Crie um array de 3 dimensões e imprima a dimensão 1 

matriz3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz3)
print(matriz3[0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


### Exercício 4

In [5]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
print('\n')
print(array[2])
print('\n')
print(array[0:2])
print('\n')
print(array[:,1:3])
print('\n')
print(array[0:2,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[7 8 9]


[[1 2 3]
 [4 5 6]]


[[2 3]
 [5 6]
 [8 9]]


[[2 3]
 [5 6]]


### Exercício 5

In [6]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
print(arr)
arrT = arr.transpose()
print(arrT)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### Exercício 6

In [7]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

for x,y,c in zip(xarr,yarr, cond):
    print(x,y,c)

a = [x if c else y for x,y,c in zip(xarr,yarr, cond) ]

print(a)

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False
[1.1, 2.2, 1.3, 1.4, 2.5]


### Exercício 7

In [22]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
A = np.arange(10)
np.save('exe7',A)
B = np.load('exe7.npy')
print(B)

[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [24]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
%time print(obj.drop_duplicates())
%time print(obj.unique())

0    c
1    a
2    d
5    b
dtype: object
CPU times: user 1.6 ms, sys: 190 µs, total: 1.79 ms
Wall time: 1.71 ms
['c' 'a' 'd' 'b']
CPU times: user 396 µs, sys: 55 µs, total: 451 µs
Wall time: 428 µs


### Exercício 9

In [10]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [39]:
data = resp.content
df = pd.read_json(data)
df

url  \
0   https://api.github.com/repos/pandas-dev/pandas...   
1   https://api.github.com/repos/pandas-dev/pandas...   
2   https://api.github.com/repos/pandas-dev/pandas...   
3   https://api.github.com/repos/pandas-dev/pandas...   
4   https://api.github.com/repos/pandas-dev/pandas...   
5   https://api.github.com/repos/pandas-dev/pandas...   
6   https://api.github.com/repos/pandas-dev/pandas...   
7   https://api.github.com/repos/pandas-dev/pandas...   
8   https://api.github.com/repos/pandas-dev/pandas...   
9   https://api.github.com/repos/pandas-dev/pandas...   
10  https://api.github.com/repos/pandas-dev/pandas...   
11  https://api.github.com/repos/pandas-dev/pandas...   
12  https://api.github.com/repos/pandas-dev/pandas...   
13  https://api.github.com/repos/pandas-dev/pandas...   
14  https://api.github.com/repos/pandas-dev/pandas...   
15  https://api.github.com/repos/pandas-dev/pandas...   
16  https://api.github.com/repos/pandas-dev/pandas...   
17  https://api.github.com/repos/pandas-dev/pandas...   
18  https://api.github.com/repos/pandas-dev/pandas...   
19  https://api.github.com/repos/pandas-dev/pandas...   
20  https://api.github.com/repos/pandas-dev/pandas...   
21  https://api.github.com/repos/pandas-dev/pandas...   
22  https://api.github.com/repos/pandas-dev/pandas...   
23  https://api.github.com/repos/pandas-dev/pandas...   
24  https://api.github.com/repos/pandas-dev/pandas...   
25  https://api.github.com/repos/pandas-dev/pandas...   
26  https://api.github.com/repos/pandas-dev/pandas...   
27  https://api.github.com/repos/pandas-dev/pandas...   
28  https://api.github.com/repos/pandas-dev/pandas...   
29  https://api.github.com/repos/pandas-dev/pandas...   

                                    repository_url  \
0   https://api.github.com/repos/pandas-dev/pandas   
1   https://api.github.com/repos/pandas-dev/pandas   
2   https://api.github.com/repos/pandas-dev/pandas   
3   https://api.github.com/repos/pandas-dev/pandas   
4   https://api.github.com/repos/pandas-dev/pandas   
5   https://api.github.com/repos/pandas-dev/pandas   
6   https://api.github.com/repos/pandas-dev/pandas   
7   https://api.github.com/repos/pandas-dev/pandas   
8   https://api.github.com/repos/pandas-dev/pandas   
9   https://api.github.com/repos/pandas-dev/pandas   
10  https://api.github.com/repos/pandas-dev/pandas   
11  https://api.github.com/repos/pandas-dev/pandas   
12  https://api.github.com/repos/pandas-dev/pandas   
13  https://api.github.com/repos/pandas-dev/pandas   
14  https://api.github.com/repos/pandas-dev/pandas   
15  https://api.github.com/repos/pandas-dev/pandas   
16  https://api.github.com/repos/pandas-dev/pandas   
17  https://api.github.com/repos/pandas-dev/pandas   
18  https://api.github.com/repos/pandas-dev/pandas   
19  https://api.github.com/repos/pandas-dev/pandas   
20  https://api.github.com/repos/pandas-dev/pandas   
21  https://api.github.com/repos/pandas-dev/pandas   
22  https://api.github.com/repos/pandas-dev/pandas   
23  https://api.github.com/repos/pandas-dev/pandas   
24  https://api.github.com/repos/pandas-dev/pandas   
25  https://api.github.com/repos/pandas-dev/pandas   
26  https://api.github.com/repos/pandas-dev/pandas   
27  https://api.github.com/repos/pandas-dev/pandas   
28  https://api.github.com/repos/pandas-dev/pandas   
29  https://api.github.com/repos/pandas-dev/pandas   

                                           labels_url  \
0   https://api.github.com/repos/pandas-dev/pandas...   
1   https://api.github.com/repos/pandas-dev/pandas...   
2   https://api.github.com/repos/pandas-dev/pandas...   
3   https://api.github.com/repos/pandas-dev/pandas...   
4   https://api.github.com/repos/pandas-dev/pandas...   
5   https://api.github.com/repos/pandas-dev/pandas...   
6   https://api.github.com/repos/pandas-dev/pandas...   
7   https://api.github.com/repos/pandas-dev/pandas...   
8   https://api.github.com/repos/pandas-dev/pandas...   
9   https://api.github.com/repos/pand

### Exercício 10

In [71]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3 as sql
from random import sample

conn = sql.connect('exe10.db')
cur = conn.cursor()
cur.execute('''CREATE TABLE IF NOT EXISTS exercicio
               (pk INTEGER PRIMARY KEY ASC AUTOINCREMENT, aleatorio INTEGER)''')
valores = range(1,100)
lista = sample(valores,k=len(valores))

for i in lista:
    cur.execute('''INSERT INTO exercicio (aleatorio) VALUES (?)''',[i])

conn.commit()

df = pd.read_sql('''SELECT * FROM exercicio''', conn)

conn.close()

df


pk  aleatorio
0    1         23
1    2         75
2    3         25
3    4         50
4    5         20
..  ..        ...
94  95         86
95  96         89
96  97         83
97  98         87
98  99         91

[99 rows x 2 columns]

# Fim


### Obrigado

### Visite o Blog da Data Science Academy - <a href="http://blog.dsacademy.com.br">Blog DSA</a>
